name: Build an image

on:
  push

jobs:
  build-image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      
      - run: ./deps.sh
      - run: ./.venv/bin/mkosi